const settings = {
  packname: 'Alson XMD ',
  author: '',
  botName: 'Alson XMD ',
  botOwner: 'Alson Machingauta',
  ownerNumber: '263786359833',
  ownerNumbers: ['263786359833', '263774265522'],
  devNumbers: ['263786359833', '263783549857'],
  commandPrefix: '.',
  newsletterJid: '0029Vb8pa9p5kg7CkpkxrR37@newsletter ',
  premiumDbPath: 'data/premium_users.db',
  channelUrl: 'https://whatsapp.com/channel/0029Vb8pa9p5kg7CkpkxrR37',
  giphyApiKey: 'qnl7ssQChTdPjsKta2Ax2LMaGXz303tq',
  commandMode: 'public',
  maxStoreMessages: 20,
  storeWriteInterval: 10000,
  description: 'This is a bot for managing group commands and automating tasks.',
  version: '3.0.7',
  updateZipUrl: 'https://github.com/alsonmachingauta06-lab/Alson bot/archive/refs/heads/main.zip',
  pairApiBase: process.env.PAIR_API_BASE || '',
  mongoUri: process.env.MONGO_URI || '',
  mongoDbName: process.env.MONGO_DB_NAME || 'Alson-XMD ',
  mongoEncryptionKey: process.env.MONGO_ENCRYPTION_KEY || '',
};

module.exports = settings;
